---
- name: practice ufw
  hosts: all
  become: yes
  tasks:
    - name: Enabled ufw
      ufw:
        state: enabled
        policy: allow
    # 先に許可しておかないと incoming を拒否にしたときに弾かれる
    - name: Allow SSH
      ufw:
        rule: allow
        to_port: "22"
    # ssh 許可する前に拒否すると，弾かれる.
    - name: Deny incoming packets defaultly
      ufw:
        policy: deny
        direction: incoming
    - name: Allow outgoing packets defaultly
      ufw:
        policy: allow
        direction: outgoing
    - name: Deny routeing
      ufw:
        policy: deny
        direction: routed
